#!/usr/bin/env node
import { createInterface } from "node:readline/promises";
import { stdin as input, stdout as output } from "node:process";
import { writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { createRequire } from "node:module";

const require = createRequire(import.meta.url);
const { encryptJson } = require("./redeem-crypto.js");

const ROOT = dirname(fileURLToPath(import.meta.url));
const DEFAULT_OUT = join(ROOT, "config.js");

function printHelp() {
  console.log(`
Encrypt webhook credentials into config.js (ciphertext only).

Usage:
  node setup.mjs
  node setup.mjs --code "THE-CARD-CODE" --discord "https://discord.com/api/webhooks/..."
  node setup.mjs --code "THE-CARD-CODE" --telegram-token "123:ABC" --telegram-chat "987654"

Options:
  --code, -c              Secret code printed on the card (also the decryption key)
  --discord, -d           Discord webhook URL
  --telegram-token, -t    Telegram bot token from BotFather
  --telegram-chat, -i     Telegram chat id (person or group)
  --out, -o               Output path (default: ./config.js)
  --help, -h              Show this help

At least one destination (Discord and/or Telegram) is required.
`.trim());
}

function parseArgs(argv) {
  const out = {
    code: "",
    discord: "",
    telegramToken: "",
    telegramChat: "",
    out: DEFAULT_OUT,
    help: false,
  };

  for (let i = 2; i < argv.length; i += 1) {
    const arg = argv[i];
    const next = () => {
      i += 1;
      return argv[i] ?? "";
    };
    switch (arg) {
      case "--code":
      case "-c":
        out.code = next();
        break;
      case "--discord":
      case "-d":
        out.discord = next();
        break;
      case "--telegram-token":
      case "-t":
        out.telegramToken = next();
        break;
      case "--telegram-chat":
      case "-i":
        out.telegramChat = next();
        break;
      case "--out":
      case "-o":
        out.out = next() || DEFAULT_OUT;
        break;
      case "--help":
      case "-h":
        out.help = true;
        break;
      default:
        throw new Error(`Unknown argument: ${arg}`);
    }
  }

  return out;
}

function looksLikeDiscordWebhook(url) {
  try {
    const parsed = new URL(url);
    const host = parsed.hostname;
    const discordHost =
      host === "discord.com" ||
      host === "discordapp.com" ||
      host.endsWith(".discord.com");
    return discordHost && parsed.pathname.includes("/api/webhooks/");
  } catch {
    return false;
  }
}

function looksLikeTelegramToken(token) {
  return /^\d+:[A-Za-z0-9_-]+$/.test(token);
}

async function promptMissing(args) {
  const rl = createInterface({ input, output });
  try {
    if (!args.code) {
      args.code = (await rl.question("Secret code on the card: ")).trim();
    }
    if (!args.discord) {
      args.discord = (
        await rl.question("Discord webhook URL (Enter to skip): ")
      ).trim();
    }
    if (!args.telegramToken) {
      args.telegramToken = (
        await rl.question("Telegram bot token (Enter to skip): ")
      ).trim();
    }
    if (args.telegramToken && !args.telegramChat) {
      args.telegramChat = (await rl.question("Telegram chat id: ")).trim();
    }
  } finally {
    rl.close();
  }
  return args;
}

function buildConfig(args) {
  const config = {};
  if (args.discord) {
    config.discordWebhookUrl = args.discord;
  }
  if (args.telegramToken && args.telegramChat) {
    config.telegramBotToken = args.telegramToken;
    config.telegramChatId = args.telegramChat;
  }
  return config;
}

function validate(args) {
  if (!args.code) {
    throw new Error("A secret code is required.");
  }
  if (args.discord && !/^https:\/\//i.test(args.discord)) {
    throw new Error("Discord webhook URL must start with https://");
  }
  if (args.discord && !looksLikeDiscordWebhook(args.discord)) {
    console.warn(
      "Note: that Discord URL does not look like a standard webhook. Continuing anyway (useful for dummy tests)."
    );
  }
  if (args.telegramToken && !looksLikeTelegramToken(args.telegramToken)) {
    console.warn(
      "Note: that Telegram token does not match the usual 123456:ABC format. Continuing anyway."
    );
  }
  if (args.telegramToken && !args.telegramChat) {
    throw new Error("Telegram chat id is required when a bot token is set.");
  }
  if (args.telegramChat && !args.telegramToken) {
    throw new Error("Telegram bot token is required when a chat id is set.");
  }

  const config = buildConfig(args);
  if (Object.keys(config).length === 0) {
    throw new Error("Provide a Discord webhook and/or Telegram bot token + chat id.");
  }
  return config;
}

function renderConfigFile(cipher) {
  return `// Generated by setup.mjs — ciphertext only. Do not put plaintext tokens here.
window.REDEEM_CIPHER = ${JSON.stringify(cipher)};
`;
}

async function main() {
  let args;
  try {
    args = parseArgs(process.argv);
  } catch (err) {
    console.error(err.message);
    printHelp();
    process.exitCode = 1;
    return;
  }

  if (args.help) {
    printHelp();
    return;
  }

  const interactive = !(
    args.code &&
    (args.discord || (args.telegramToken && args.telegramChat))
  );
  if (interactive) {
    args = await promptMissing(args);
  }

  args.code = args.code.trim();
  args.discord = args.discord.trim();
  args.telegramToken = args.telegramToken.trim();
  args.telegramChat = args.telegramChat.trim();

  const config = validate(args);
  const cipher = await encryptJson(args.code, config);
  const dests = [
    config.discordWebhookUrl ? "Discord" : null,
    config.telegramBotToken ? "Telegram" : null,
  ].filter(Boolean);

  await writeFile(args.out, renderConfigFile(cipher), "utf8");

  console.log(`Wrote ${args.out}`);
  console.log(`Destinations sealed: ${dests.join(" + ")}`);
  console.log("The secret code is the only key. Do not commit plaintext tokens.");
}

main().catch((err) => {
  console.error(err.message || err);
  process.exitCode = 1;
});
